version: "3"
services:
  mysql:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  php:
    build: ./php
    depends_on:
      - mysql
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ../:/var/www/html
    logging:
      options:
        max-size: "10m"
        max-file: "5"

volumes:
   db:
